name: Run Ghost Explorer

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

# Default public env vars
env:
  LOG_TIMEZONE: EST

jobs:
  setup-and-run-bot:
    name: Setup and Run Ghost Explorer
    runs-on: ubuntu-latest
    outputs:
      data-changed: ${{ steps.verify-changed-files.outputs.files_changed }}
    steps:
      - name: Checkout Local Repo
        uses: actions/checkout@v4

      - name: Convert Repo Name to Lowercase
        id: set-lowercase-repo-name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ env.REPO_NAME }}:latest

      # Run the Python app inside the prebuilt Docker container
      - name: Run Ghost Explorer in Docker
        run: |
          docker run --env SUPER_SECRET_URL="${{ secrets.SUPER_SECRET_URL }}" \
                     --env SUPER_SECRET_PARAMS_1="${{ secrets.SUPER_SECRET_PARAMS_1 }}" \
                     --env SUPER_SECRET_PARAMS_2="${{ secrets.SUPER_SECRET_PARAMS_2 }}" \
                     --env SUPER_SECRET_PARAMS_3="${{ secrets.SUPER_SECRET_PARAMS_3 }}" \
                     ghcr.io/${{ env.REPO_NAME }}:latest

      - name: Verify Changed files
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v20
        with:
          files: |
            output/**
            output
            *.csv

      - name: Commit and Push Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated Ghost Explore Sites
          branch: main
        env:
          GIT_USER_NAME: ${{ secrets.USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

